Repository varunvora/alcoding, pull requests merged in 2019-03, with the labels that each got.

#4 Mapping handles to USN
  database/contest_ranks/codechef-dec18.in
  database/contest_ranks/codechef-jan19.in
  database/contest_ranks/codechef-oct18.in
  database/db.json
  database/unmapped_handles.out
  scoreboard.csv
Labels: Priority: High, Status: Review Needed, Type: Maintenance

#7 Mapped 2 2018 USNs:
  database/contest_ranks/codechef-dec18.in
  database/contest_ranks/codechef-feb19.in
  database/contest_ranks/codechef-nov18.in
  database/contest_ranks/codechef-oct18.in
  database/db.json
  database/db_tools.py
  database/unmapped_handles.out
  scoreboard.csv
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#8 Kickstart scraper
  scrapers/codejam.py
  scrapers/google.py
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#10 Hackerearth
  database/README.md
  database/contest_ranks/hackerearth-feb-circuits19.in
  database/contest_ranks/hackerearth-feb-easy-2019.in
  database/contest_ranks/hackerearth-jan-easy-2019.in
  database/db.json
  executor.sh
  scoreboard.csv
  scrapers/README.md
  scrapers/hackerearth.py
Labels: Priority: High, Status: Accepted, Type: Bug

#11 March19 long
  database/README.md
  database/contest_ranks/codechef-mar19.in
  database/contest_ranks/codechef-nov18.in
  database/db.json
  database/unmapped_handles.out
  executor.sh
  scoreboard.csv
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#13 Added ratings for Codechef Long June18 - Sept18
  database/README.md
  database/contest_ranks/codechef-aug18.in
  database/contest_ranks/codechef-july18.in
  database/contest_ranks/codechef-june18.in
  database/contest_ranks/codechef-sept18.in
  database/db.json
  database/unmapped_handles.out
  executor.sh
  scoreboard.csv
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#14 tested impact of rating and volatility for unknown users
  README.md
  database/contest_ranks/codechef-june18.in
  database/contest_ranks/hackerearth-feb-circuits19.in
  database/contest_ranks/kickstart-a-2019.in
  database/db.json
  database/db_tools.py
  executor.sh
  ratings/processor.py
  scoreboard.csv
Labels: Priority: Critical, Status: Completed, Type: Bug
