Repository varunvora/alcoding, pull requests merged in 2019-04, with the labels that each got.

#20 updated database with 2020, 2021
  database/db.json
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#19 Added remove_unmapped_handles_from_rank_file function.
  database/README.md
  database/contest_ranks/hackerearth-april-easy-2019.in
  database/db.json
  database/db_tools.py
  executor.sh
  scoreboard.csv
  scrapers/hackerearth.py
Labels: Priority: Medium, Status: Revision Needed, Type: Enhancement

#21 Updated Codejam 2019 - qualifers and 1a ratings.
  database/README.md
  database/contest_ranks/codejam-1a-2019.in
  database/contest_ranks/codejam-qualification-2019.in
  database/db.json
  executor.sh
  scoreboard.csv
  scrapers/google.py
  tests/contest_rank_integrity_tests.py
Labels: Priority: Medium, Status: Accepted, Type: Maintenance

#24 Unmapped handles
  database/contest_ranks/codechef-april19.in
  database/contest_ranks/codechef-aug18.in
  database/contest_ranks/codechef-dec18.in
  database/contest_ranks/codechef-feb19.in
  database/contest_ranks/codechef-jan19.in
  database/contest_ranks/codechef-july18.in
  database/contest_ranks/codechef-june18.in
  database/contest_ranks/codechef-mar-cookoff19.in
  database/contest_ranks/codechef-mar-lunchtime19.in
  database/contest_ranks/codechef-mar19.in
  database/contest_ranks/codechef-nov18.in
  database/contest_ranks/codechef-oct18.in
  database/db.json
  database/unmapped_handles.out
  scoreboard.csv
Labels: Priority: High, Status: Accepted, Type: Maintenance

#25 Updated ratings for April cookoff 2019 - Codechef.
  database/README.md
  database/contest_ranks/codechef-april-cookoff19.in
  database/db.json
  executor.sh
  ratings/elo.py
  scoreboard.csv
Labels: Priority: Medium, Status: Accepted, Type: Maintenance
